# Site settings
title: 个人博客
email: hqc2010@gmail.com
description: yunjing's personal website
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://0x5143.github.io" # the base hostname & protocol for your site
# twitter_username: hqcchina
github_username: 0x5143
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/0x5143/0x5143.github.com
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/0x5143/0x5143.github.com/new/master
#########################################
# disqus.com commenting system.
disqus_shortname: 0x5143
disqus_url: "https://0x5143.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
